config/routes.rb
Codeshare::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :users

  resources :snippets

  resources :comments

  get '/' => "users#welcome"
  root to: 'users#welcome'

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :set_snippet, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show, :index]

  # GET /snippets
  # GET /snippets.json
  def index
    @snippets = Snippet.all
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new(snippet_params)

    if !@snippet.user.eql? (current_user)
      @snippet.errors.add(:base, "You're messing with me, huh?")
      raise ActiveRecord::RecordInvalid.new(@snippet)
    end

    respond_to do |format|
      if @snippet.save
        format.html { redirect_to @snippet, notice: 'Snippet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @snippet }
      else
        format.html { render action: 'new' }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update

    if !@snippet.user.eql? (current_user)
      @snippet.errors.add(:base, "You're messing with me, huh?")
      raise ActiveRecord::RecordInvalid.new(@snippet)
    end

    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to @snippet, notice: 'Snippet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    if (@snippet.user.eql?( current_user ))
      user = @snippet.user
      @snippet.destroy
      respond_to do |format|
        format.html { redirect_to user_path(user) }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to snippet_path(@snippet) }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:code, :title, :user_id, :lang)
    end
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/snippets/_form.html.erb
<%= form_for(@snippet) do |f| %>
  <% if @snippet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>

      <ul>
      <% @snippet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title, { class: 'form-control', placeholder: 'Best piece of code ever' } %>
    </div>
    <div class="field">
      <%= f.label :lang %><br />
      <%= f.select(:lang, ['C', 'C++', 'Clojure', 'CSS', 'Delphi', 'diff', 'ERB', 'Go', 'Groovy', 'HAML', 'HTML', 'Java', 'JavaScript', 'JSON', 'Lua', 'PHP', 'Python', 'Ruby', 'Sass', 'SQL', 'Taskpaper', 'XML', 'YAML'], class: 'form-control') %>
    </div>
    <div class="field">
      <%= f.label :code %><br />
      <%= f.text_area :code, { class: 'form-control', rows: 12 } %>
    </div>
    <div class="actions">
      <%= f.submit 'Save snippet!', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<%= render 'form' %>

app/views/snippets/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Snippet Title</th>
    </tr>
  </thead>

  <tbody>
    <% @snippets.each do |snippet| %>
      <tr>
        <td><%= link_to snippet.title, snippet %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snippet', new_snippet_path, class: 'btn btn-primary' %>

app/views/snippets/new.html.erb
<h1>New snippet</h1>

<%= render 'form' %>

<%= link_to 'Back', snippets_path %>

app/views/snippets/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h2><%= @snippet.title %></h2>
    <h5>Language: <%= @snippet.lang %></h5>
  </div>
  <div class="col-md-6 text-right">
    <% if @snippet.user.eql? ( current_user ) %>
        <%= link_to 'Edit', edit_snippet_path(@snippet), class: 'btn btn-warning' %> <%= link_to 'Delete', snippet_path(@snippet), { method: :delete, class: 'btn btn-danger'} %>
    <% end %>
  </div>
</div>

<div class="row">
  <%= raw CodeRay.scan(@snippet.code, @snippet.lang).div(:line_numbers => :inline) %>
</div>




<% @snippet.comments.each do |comment| %>
    <div class="row">
    <div class="col-md-12 bg-warning">
      <italics><%= link_to 'commenter #' + comment.user.id.to_s, user_path(comment.user) %> wrote:</italics>
      <%= comment.content %>
      <br/>
      <% if comment.user.eql? (current_user) %>
      <%= link_to 'Edit', edit_comment_path(comment) %>  | <%= link_to 'Delete', comment_path(comment), method: :delete %>
      <% end %>
    </div>
    </div>
    <br/>
<% end %>

<% if user_signed_in? %>
<div class="row comment-editor">
  <%= form_for(Comment.new) do |f| %>
      <div class="field">
        <%= f.label :content %><br />
        <%= f.text_area :content, { class: 'form-control', rows: 5 } %>
      </div>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :snippet_id, :value => @snippet.id %>
      <div class="actions">
        <%= f.submit 'Post comment', class: 'btn btn-primary' %>
      </div>
  <% end %>
</div>
<% end %>