config/routes.rb
Codeshare::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :users

  resources :snippets

  resources :comments

  get '/' => "users#welcome"
  root to: 'users#welcome'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable, :omniauth_providers => [:facebook, :twitter]

  has_many :comments
  has_many :snippets
  accepts_nested_attributes_for :snippets
  accepts_nested_attributes_for :comments
  validates_uniqueness_of :email, :allow_blank => true

  def self.find_for_facebook_oauth(auth)
    where(:fb_uid => auth.uid).first_or_create do |user|
      user.fb_uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.find_for_twitter_oauth(auth)
    where(:vk_uid => auth.uid).first_or_create do |user|
      user.vk_uid = auth.uid
      user.email = auth.info.nickname + '@twitter.com'
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show, :welcome]

  # GET /
  def welcome
    if user_signed_in?
      redirect_to user_path(current_user)
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if !@user.eql? (current_user)
      @user.errors.add(:base, "You're messing with me, huh?")
      raise ActiveRecord::RecordInvalid.new(@user)
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if !@user.eql? (current_user)
      @user.snippets.each {|snippet| snippet.destroy }
      @user.comments.each {|comment| comment.destroy }
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url }
        format.json { head :no_content }
      end
    else
      redirect_to user_path (current_user)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% if @user.eql? (current_user) %>
<div class="row coda-editor">
  <%= form_for(Snippet.new) do |f| %>
      <div class="field">
        <%= f.label :title %><br />
        <%= f.text_field :title, { class: 'form-control', placeholder: 'Best piece of code ever' } %>
      </div>
      <div class="field">
        <%= f.label :code %><br />
        <%= f.text_area :code, { class: 'form-control', rows: 12 } %>
      </div>
      <div class="field">
        <%= f.label :lang %><br />
        <%= f.select(:lang, ['C', 'C++', 'Clojure', 'CSS', 'Delphi', 'diff', 'ERB', 'Go', 'Groovy', 'HAML', 'HTML', 'Java', 'JavaScript', 'JSON', 'Lua', 'PHP', 'Python', 'Ruby', 'Sass', 'SQL', 'Taskpaper', 'XML', 'YAML'], class: 'form-control') %>
      </div>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <div class="actions">
        <%= f.submit 'Save snippet!', class: 'btn btn-primary' %>
      </div>
  <% end %>
</div>
<% end %>

<% if @user.snippets.any? %>
<div class="row">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Snippet title</th>
      <th>Edited</th>
      <% if user_signed_in? %>
      <th></th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @user.snippets.each do |snippet| %>
    <tr>
      <td style="vertical-align: middle"><%= link_to snippet.title, snippet_path(snippet) %></td>
      <td style="vertical-align: middle"><%= snippet.updated_at.to_s %></td>
      <% if user_signed_in? %>
      <td class="text-right"><%= link_to 'edit', edit_snippet_path(snippet), {class: 'btn btn-warning btn-mini'} %>
      <%= link_to 'delete', snippet_path(snippet), {method: :delete, class: 'btn btn-danger btn-mini'} %></td>
      <% end %>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/users/welcome.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1>CodaShare</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <p class="text-center">Hi! It's codashare, a great place to save your greatest code snippets and get famous. Log in to post your code and comments. </p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <a class="btn btn-primary" href="<%= new_user_session_path %>">Log in</a>
      <a class="btn btn-primary" href="<%= new_user_registration_path %>">Join!</a>
    </div>
  </div>
</div>