config/routes.rb
Codeshare::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :users

  resources :snippets

  resources :comments

  get '/' => "users#welcome"
  root to: 'users#welcome'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codashare</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">codashare</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li class="<%= raw request.original_url.end_with?('users/' + current_user.id.to_s) ? 'active' : '' %>"><a href="<%= user_path(current_user) %>">My snippets</a></li>
        <% end %>
        <li class="<%= raw request.original_url.end_with?('snippets') ? 'active' : '' %>"><a href="<%= snippets_path %>">All snippets</a></li>
      </ul>
      <%#<form class="navbar-form navbar-left" role="search">                               %>
      <%#  <div class="form-group">                                                         %>
      <%#    <input type="text" class="form-control" placeholder="Search">                  %>
      <%#  </div>                                                                           %>
      <%#  <button type="submit" class="btn btn-default">Submit</button>                    %>
      <%#</form>                                                                            %>
      <div class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger navbar-btn'  %>
        <% else %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn'  %>
        <% end %>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <div class="row">
    <% if (notice) %>
    <div class="alert alert-info alert-dismissable col-md-4 col-md-offset-4">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <p id="notice"><%= notice %></p>
    </div>
    <% end %>
  </div>
  <div class="col-md-12">
    <%= yield %>
  </div>
</div>

</body>
</html>